apiVersion: v1
kind: Service
metadata:
  name: kube-forc1cs-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: kube-forc1cs
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 32001
      protocol: TCP
